#################################################
# This file is a sample of some things you 
# can do with this leader key setup. The 
# lua prioritizes home.toml, then work.toml,
# then falls back to this sample.toml. If you
# want different profile names, you can edit
# the config-reading code at the top of init.lua.
# You don't need to know lua to change it, just
# follow the pattern.
#################################################


# settings
leader_key = "f18"
auto_reload = true
toast_on_reload = false

# set a key to an app
t = "Terminal"

# pass an array to change the label for the action in the popup
v = ["Visual Studio Code", "VS Code"]

# create groups to nest actions under a
# sequence of keypresses
[l]
# the "label" key is reserved to change the label of the group
label = "[links]"
g = "https://github.com"
b = "https://bsky.app"
t = "https://twitter.com"

# groups can be nested too!
[l.m]
label = "[me]"
g = "https://github.com/saml-dev"
b = "https://bsky.app/profile/saml.dev"
t = "https://twitter.com/saml_dev"
