[d]
"=" = [ "cmd:/opt/homebrew/bin/hs -c \"formatClip()\"", "Evaluate clipboard",]
O = [ "cmd:/opt/anaconda3/bin/python3 /Users/jason/Scripts/Text_Manipulation/text_processor/interfaces/hotkey_gui.py", "Edit clipboard with StringThing",]
o = [ "cleanshot://capture-text?linebreaks=false\n\ncleanshot://capture-text?linebreaks=false\n\n", "OCR",]
p = [ "cmd:/Applications/Privileges.app/Contents/MacOS/privilegescli -a", "Privileges",]
r = [ "kmtrigger://macro=Open%20most%20recently%20downloaded%20file", "Recent download",]
z = [ "function:redo", "Redo last command",]
label = "Default"

[F]
"." = [ "cmd:open /Users/jason/.zshrc -b \"com.microsoft.vscodeinsiders\"", ".zshrc",]
a = [ "cmd:open \"/Users/jason/Library/CloudStorage/OneDrive-Personal/1 - Work/---- - workers' compensation resources/SOURCES - AMAG - AMA - Guides for the Evaluation of Permanent Impairment/2001, AMA Guides, Fifth Edition/AMA Guides to the Evaluation of Permanent Impairment - 5th Ed., 2001.pdf\" -b \"net.sourceforge.skim-app.skim\"", "AMA Guides",]
c = [ "cmd:open \"/Users/jason/Library/Application Support/Claude/claude_desktop_config.json\" -b \"com.microsoft.vscodeinsiders\"", "Claude MCPs",]
k = [ "cmd:open \"/Users/jason/.config/karabiner/karabiner.json\" -b \"com.microsoft.vscodeinsiders\"", "Karabiner rules",]
l = [ "cmd:open \"/Users/jason/Library/Application Support/Leader Key/config.json\" -b \"com.microsoft.vscodeinsiders\"", "Leaderkey shortcuts",]
p = [ "cmd:open \"/Users/jason/Library/CloudStorage/OneDrive-Personal/1 - Work/---- - workers' compensation resources/SOURCES - PDRS - Permanent Disability Rating Schedules/New Schedule - 2005 Schedule for Rating Permanent Disabilities PDRS - DOI on or after 2005.pdf\" -b \"net.sourceforge.skim-app.skim\"", "PDRS",]
s = [ "cmd:python3 /Users/jason/Scripts/Application_Specific/Leaderkey/jjk_SortLeaderkey/jjk_sort_leaderkey_config.py", "Sort leaderkey shortcuts",]
label = "Files"

[R]
P = [ "cmd:open -g \"rectangle-pro://execute-action?name=pin\"", "Toggle Pin mode",]
p = [ "cmd:open -g \"rectangle-pro://execute-action?name=reflow-pin\"", "Reflow Pinned app",]
r = [ "cmd:open -g \"rectangle-pro://execute-action?name=reflow-pin\"", "Reflow Pinned app",]
t = [ "cmd:open -g \"rectangle-pro://execute-action?name=pin\"", "Toggle Pin mode",]
label = "Rectangle"

[S]
n = [ "cmd:python3 /Users/jason/Scripts/Application_Specific/Meruscase/jjk_Rename_MerusScans.py --source clipboard --dest paste", "Name scan in Merus",]
r = [ "raycast://extensions/koinzhang/text-shortcuts/shortcut-library", "Raycast text extension",]
s = [ "cmd:python3 /Users/jason/Scripts/Application_Specific/Leaderkey/jjk_SortLeaderkey/jjk_sort_leaderkey_config.py", "Sort config",]
label = "Misc. Scripts"

[a]
1 = [ "/Applications/1Password.app", "1Password",]
8 = [ "/Applications/8x8 Work.app", "8x8",]
a = [ "/Applications/Adobe Acrobat DC/Adobe Acrobat.app", "Acrobat",]
b = ["/Applications/Brave Browser.app", "Brave",]
c = [ "/Applications/Visual Studio Code - Insiders.app", "Code",]
d = ["/Applications/Dia.app", "Dia",]
e = [ "/Applications/Microsoft Edge.app", "Edge",]
f = [ "/Applications/QSpace Pro.app", "Finder",]
g = [ "/Applications/GitHub Desktop.app", "GitHub Desktop",]
i = ["/Users/jason/Applications/iTerm.app", "iTerm",]
o = ["/Applications/Microsoft Outlook.app", "Outlook",]
p = ["/Applications/Proton Mail.app", "Proton Mail",]
r = ["/Users/jason/Applications/Setapp/GoodTask.app", "Reminders",]
s = ["/System/Applications/Messages.app", "SMS",]
t = ["/Applications/Microsoft Teams.app", "Teams",]
w = ["/Applications/Microsoft Word.app", "Word",]
x = ["/Applications/Microsoft Excel.app", "Excel",]
label = "Applications"

[b]
a = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py td_to_aww  --source clipboard --dest paste", "AWW from TTD",]
t = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py aww_to_td  --source clipboard --dest paste", "TTD from AWW",]
label = "Benefit rates"

[c]
l = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py lowercase --source clipboard --dest paste", "lower",]
s = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py sentence_case --source clipboard --dest paste", "Sentence",]
t = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py title_case --source clipboard --dest paste", "Title",]
u = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py uppercase --source clipboard --dest paste", "UPPER",]
label = "Case changers"

[d]
a = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py date_alpha --source clipboard --dest paste", "Alpha - MMMM D, YYYY",]
d = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py date_diff --source clipboard --dest paste", "Date diff",]
f = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py date_file --source clipboard --dest paste", "File - YYYY.MM.DD",]
i = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py date_iso --source clipboard --dest paste", "ISO - YYYY-MM-DD",]
l = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py date_long --source clipboard --dest paste", "Long - MM/DD/YYYY",]
m = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py date_medium --source clipboard --dest paste   ", "Medium - M/D/YYYY",]
p = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py date_pad --source clipboard --dest paste", "Padded medium - MM/DD/YYYY",]
r = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py format_relative_date --source clipboard --dest paste", "Relative date",]
label = "Date scripts"

[f]
D = [ "/Applications/DEVONthink.app", "DEVONthink",]
S = [ "cmd:open /Users/jason/Scripts/Workspaces/Scripts.code-workspace", "Scripts workspace",]
a = [ "cmd: open -a \"Qspace Pro\" \"/Applications\"", "Applications",]
c = [ "cmd:open -a \"Qspace Pro\" \"/Users/jason/Library/CloudStorage/OneDrive-BoxerandGerson,LLP/Documents/Cases\"", "Cases",]
d = [ "cmd: open -a \"Qspace Pro\" \"/Users/jason/Downloads\"", "Downloads",]
f = [ "cmd: open -a \"Qspace Pro\"", "Finder",]
g = [ "cmd: open -a \"Qspace Pro\" \"/Users/jason/Gits\"", "Gits",]
h = [ "cmd: open -a \"Qspace Pro\" \"/Users/jason/.hammerspoon\"", "Hammerspoon",]
j = [ "cmd: open -a \"Qspace Pro\" \"/Users/jason\"", "Home",]
l = [ "cmd: open -a \"Qspace Pro\" \"/Users/jason/Library/CloudStorage/OneDrive-Personal/1 - Work/---- - workers' compensation resources\"", "Library",]
p = [ "cmd: open -a \"Qspace Pro\" \"/Users/jason/Documents/programming\"", "Programs",]
s = [ "cmd: open -a \"Qspace Pro\" \"/Users/jason/Scripts\"", "Scripts",]
w = [ "cmd: open -a \"Qspace Pro\" \"/Users/jason/Scripts/Workspaces\"", "Workspaces",]
label = "Folders"

[m]
H = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_horizontal_rule --source clipboard --dest paste", "Horizontal line",]
b = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_bold --source clipboard --dest paste", "Bold",]
i = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_italic --source clipboard --dest paste", "Italics",]
l = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_link --source clipboard --dest paste", "Link",]
r = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py remove_markdown --source clipboard --dest paste", "Remove markdown",]
s = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_strikethrough --source clipboard --dest paste", "Strikethrough",]
u = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_underline --source clipboard --dest paste", "Underline",]
label = "Markdown"

[s]
C = [ "cleanshot://capture-area", "Copy to clipboard",]
a = [ "cleanshot://capture-area?action=annotate", "Annotate",]
c = [ "cleanshot://capture-text?linebreaks=false\n\n", "OCR",]
p = [ "cleanshot://capture-area?action=pin", "Pin",]
s = [ "cleanshot://capture-area?action=save", "Save",]
label = "Screenshots"

[w]
"'" = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py wrap_single_quotes --source clipboard --dest paste", "\"\"",]
9 = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py wrap_parentheses --source clipboard --dest paste", "()",]
b = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py wrap_brackets --source clipboard --dest paste", "[]",]
c = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py wrap_curly_braces --source clipboard --dest paste", "{}",]
q = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py wrap_quotes --source clipboard --dest paste", "\"\"",]
label = "Wrappers by Py"

[a.B]
b = ["/Applications/Brave Browser.app", "Brave",]
d = ["/Applications/Dia.app", "Dia",]
e = [ "/Applications/Microsoft Edge.app", "Edge",]
o = ["/Applications/Orion.app", "Orion"]
s = ["/Applications/SigmaOS.app", "SigmaOS"]
t = ["/Applications/Tor Browser.app", "Tor Browser"]
z = ["/Applications/Zen.app", "Zen"]   
label = "Browsers"

[m.L]
o = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_ordered_list --source clipboard --dest paste", "Ordered List",]
u = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_unordered_list --source clipboard --dest paste", "Unordered List",]
label = "Lists"

[m.h]
1 = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_heading --source clipboard --dest paste --level 1", "1 Heading 1",]
2 = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_heading --source clipboard --dest paste --level 2", "2 Heading 2",]
3 = [ "cmd:python3 ~/Scripts/Text_Manipulation/text_processor/interfaces/cli.py markdown_heading --source clipboard --dest paste --level 3", "3 Heading 3",]
label = "Headings"
